# this need to be apply first before installing certificate for any url
# =====================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cynthia4ukibe@gmail.com
    privateKeySecretRef:
      name: production-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx